name = "covenant-signing-agent"
main = "app/workers/signing_agent/index.js"
compatibility_date = "2025-12-17"
workers_dev = false
preview_urls = false

[[d1_databases]]
binding = "DB"
database_name = "covenant"
database_id = "eeadb9e3-3ad5-4604-a870-84732a10c3e8"

[[durable_objects.bindings]]
name = "SIGNING_AGENT"
class_name = "SigningAgentWorker"

[[migrations]]
tag = "v1"
new_classes = ["SigningAgentWorker"]

[[rules]]
globs = ["**/*.yml", "**/*.yaml"]
type = "Text"
fallthrough = true
