launchpad:
  seller_address: bc1plgf5509deuezu7xsekk4f074x06lcdexse7rrlkfd26d6ha9s55quhyyqt
  collections:
    - slug: mint
      title: Bitcoin Knotzis
      parent_inscription_id: 1949dcdc265f64791e98900107e420ea7d26722db650692961243d84b0516b90i0
      price_sats: 3630
      lowest_inscription_utxo_size: 1
      payment_address: 3DBkjGpmuQ5TQXMqBZEMQuBViCjyfShM4r
      op_return: true

selling: []
